### ISSUE TITLE
issue of 'convert_to_tensor v2 with dispatch' and example information

### ISSUE THREAD

**Issue by kaintels** [DarshanDeshpande/tf-madgrad#1]
Hello.
Thank you for sharing great work.

When running the example, the following error is displayed.

```python
AttributeError: module 'tensorflow.python.framework.ops' has no attribute 'convert_to_tensor v2 with dispatch'
```

my TensorFlow version is 2.3.0.
I downgrade to 2.2.0, but the result is the same.

Is there any way to fix something?

Thank you in advance.

Best Regards,

Seungwoo

**Comment by DarshanDeshpande** [comment]
Thanks for reporting this. I wrongly assumed that  `convert_to_tensor_v2_with_dispatch` was available in versions below 2.4.0. I have merged a [fix](https://github.com/DarshanDeshpande/tf-madgrad/commit/25ac5b5641fd4882ccb23804ef733ba4d27c0d21) and updated the PyPi version as well. Please try again and let me know if you have any issues

**Comment by kaintels** [comment]
thank you, it is work,

I ran the code in the examples folder, but it was not trained well. I think the learning rate [value](https://github.com/DarshanDeshpande/tf-madgrad/blob/25ac5b5641fd4882ccb23804ef733ba4d27c0d21/examples/mnist_example.py#L47) is different from that of colab. 
I modified the value and open a pull request. Please review.

have a nice day.

Seungwoo

**Comment by DarshanDeshpande** [comment]
Addressed in the PR thread. Closing this issue
