### ISSUE TITLE
By running the copy of the colab I have the following error. on my computer it runs without error

### ISSUE THREAD

**Issue by dimkiriakos** [DarshanDeshpande/tf-madgrad#3]
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:375: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-18-c3a6e0916264> in <module>()
      2 epochs = 15
      3 
----> 4 model.compile(loss="categorical_crossentropy", optimizer=MadGrad(lr=1e-3), metrics=["accuracy"])
      5 model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.1)

5 frames
/usr/local/lib/python3.7/dist-packages/keras/optimizers.py in get(identifier)
    131   else:
    132     raise ValueError(
--> 133         'Could not interpret optimizer identifier: {}'.format(identifier))

ValueError: Could not interpret optimizer identifier: <madgrad.madgrad.MadGrad object at 0x7f8690765110>

**Comment by DarshanDeshpande** [comment]
I am able to reproduce this on Colab. Seems more like TF 2.6.0 is the issue. It works fine with TF <=2.5.
I am a bit busy at the moment to look into this so if you are willing to contribute and find a fix then please let me know.
